// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAogN5R7BYDveL5MjWEll69yQlDIQgXaRM',
    appId: '1:59805035605:web:82da0c22106e69f91e38dc',
    messagingSenderId: '59805035605',
    projectId: 'notes-app-d9cae',
    authDomain: 'notes-app-d9cae.firebaseapp.com',
    storageBucket: 'notes-app-d9cae.appspot.com',
    measurementId: 'G-G6CBD7Z57N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP3dInt3FL8DPA3qm9S4_snjiy-zCGupA',
    appId: '1:59805035605:android:983bb065971b4c871e38dc',
    messagingSenderId: '59805035605',
    projectId: 'notes-app-d9cae',
    storageBucket: 'notes-app-d9cae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB51LkE8_ZQMf8DWmRv226i8oC4973AS2E',
    appId: '1:59805035605:ios:586cfd6b0795f6821e38dc',
    messagingSenderId: '59805035605',
    projectId: 'notes-app-d9cae',
    storageBucket: 'notes-app-d9cae.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB51LkE8_ZQMf8DWmRv226i8oC4973AS2E',
    appId: '1:59805035605:ios:586cfd6b0795f6821e38dc',
    messagingSenderId: '59805035605',
    projectId: 'notes-app-d9cae',
    storageBucket: 'notes-app-d9cae.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAogN5R7BYDveL5MjWEll69yQlDIQgXaRM',
    appId: '1:59805035605:web:a9a254f6473646a41e38dc',
    messagingSenderId: '59805035605',
    projectId: 'notes-app-d9cae',
    authDomain: 'notes-app-d9cae.firebaseapp.com',
    storageBucket: 'notes-app-d9cae.appspot.com',
    measurementId: 'G-58NLL22G0W',
  );
}
